inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

Style/DotPosition:
  EnforcedStyle: leading

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

#Metrics/LineLength:
#  Max: 100

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

#Metrics/MethodLength:
#  Max: 20

#Metrics/AbcSize:
#  Max: 20

# Only relevant for Rails 5.
Rails/HttpPositionalArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
