Rails:
  Enabled: true

Style/DotPosition:
  EnforcedStyle: leading

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

# Only relevant for Rails 5.
Rails/HttpPositionalArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
